name: AttractiveAlbania Draft Builder

on:
  schedule:
    - cron: "45 15 * * *"
  workflow_dispatch: {}   # allow manual runs

concurrency:
  group: attractivealbania-draft-builder
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (with retry)
        run: |
          pip install -r requirements.txt || \
          (sleep 3 && pip install -r requirements.txt)

      - name: Validate required secrets
        run: |
          required=(WP_BASE_URL WP_USERNAME WP_APP_PASSWORD OPENROUTER_API_KEY OPENROUTER_MODEL)
          missing=0
          for k in "${required[@]}"; do
            if [ -z "${!k}" ]; then
              echo "::error ::Missing required secret: $k"
              missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then
            exit 1
          fi
        env:
          WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}

      - name: Create .env file (if your script expects it)
        run: |
          cat > .env <<'EOF'
          WP_BASE_URL=${{ secrets.WP_BASE_URL }}
          WP_USERNAME=${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD=${{ secrets.WP_APP_PASSWORD }}

          LLM_PROVIDER=${{ secrets.LLM_PROVIDER || 'OPENROUTER' }}
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL=${{ secrets.OPENROUTER_MODEL }}

          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL=${{ secrets.OPENAI_MODEL }}

          WP_DEFAULT_AUTHOR_ID=${{ secrets.WP_DEFAULT_AUTHOR_ID }}
          WP_DEFAULT_CATEGORY_ID=${{ secrets.WP_DEFAULT_CATEGORY_ID }}
          TARGET_LANGUAGE=${{ secrets.TARGET_LANGUAGE }}
          MIN_WORDS=${{ secrets.MIN_WORDS }}
          MAX_WORDS=${{ secrets.MAX_WORDS }}
          FALLBACK_TOPICS=${{ secrets.FALLBACK_TOPICS }}
          TARGET_DRAFT_POOL=${{ secrets.TARGET_DRAFT_POOL }}
          CREATE_LIMIT_PER_RUN=${{ secrets.CREATE_LIMIT_PER_RUN }}
          DAILY_LOCK=false
          EOF

      - name: Run draft builder
        env:
          WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER || 'OPENROUTER' }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          WP_DEFAULT_AUTHOR_ID: ${{ secrets.WP_DEFAULT_AUTHOR_ID }}
          WP_DEFAULT_CATEGORY_ID: ${{ secrets.WP_DEFAULT_CATEGORY_ID }}
          TARGET_LANGUAGE: ${{ secrets.TARGET_LANGUAGE }}
          MIN_WORDS: ${{ secrets.MIN_WORDS }}
          MAX_WORDS: ${{ secrets.MAX_WORDS }}
          FALLBACK_TOPICS: ${{ secrets.FALLBACK_TOPICS }}
          TARGET_DRAFT_POOL: ${{ secrets.TARGET_DRAFT_POOL }}
          CREATE_LIMIT_PER_RUN: ${{ secrets.CREATE_LIMIT_PER_RUN }}
          DAILY_LOCK: "false"
        run: python ai_poster.py
